"""empty message

Revision ID: 46a3c89c307f
Revises: b05bdce76a2c
Create Date: 2023-03-16 10:48:39.970802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a3c89c307f'
down_revision = 'b05bdce76a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('commercial_names', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication', 'commercial_names')
    # ### end Alembic commands ###
