"""empty message

Revision ID: b05bdce76a2c
Revises: 09408cd580cf
Create Date: 2023-03-15 18:37:27.220503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05bdce76a2c'
down_revision = '09408cd580cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('concentration_APD', sa.Float(), nullable=True),
    sa.Column('concentration_TOB', sa.Float(), nullable=True),
    sa.Column('emergency_case', sa.String(length=2000), nullable=True),
    sa.Column('side_effect', sa.String(length=500), nullable=True),
    sa.Column('side_effect_MP', sa.String(length=255), nullable=True),
    sa.Column('a_ping', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=255), nullable=True),
    sa.Column('indications', sa.String(length=2000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('treat_for', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_link', sa.String(length=500), nullable=True),
    sa.Column('additional_info', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('profile_picture', sa.String(length=1000), nullable=True),
    sa.Column('date_of_birth', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=500), nullable=True),
    sa.Column('creation_date', sa.String(length=500), nullable=True),
    sa.Column('last_modification_date', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MedLog',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.String(length=120), nullable=True),
    sa.Column('last_modification_date', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'medication_id')
    )
    op.create_table('MedRes',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'medication_id')
    )
    op.create_table('MedVid',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('video_id', 'medication_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MedVid')
    op.drop_table('MedRes')
    op.drop_table('MedLog')
    op.drop_table('video')
    op.drop_table('user')
    op.drop_table('resource')
    op.drop_table('medication')
    # ### end Alembic commands ###
